LOAD DATA LOCAL INFILE 'C:\\openalex\\institutions.csv' REPLACE INTO TABLE openalex.institutions FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (id, ror, display_name, country_code, type, homepage_url, image_url, image_thumbnail_url, display_name_acroynyms, display_name_alternatives, works_count, cited_by_count, works_api_url, updated_date);
LOAD DATA LOCAL INFILE 'C:\\openalex\\institutions_ids.csv' REPLACE INTO TABLE openalex.institutions_ids FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (institution_id, openalex, ror, grid, wikipedia, wikidata, mag);
LOAD DATA LOCAL INFILE 'C:\\openalex\\institutions_geo.csv' REPLACE INTO TABLE openalex.institutions_geo FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (institution_id, city, geonames_city_id, region, country_code, country, latitude, longitude);
LOAD DATA LOCAL INFILE 'C:\\openalex\\institutions_associated_institutions.csv' REPLACE INTO TABLE openalex.institutions_associated_institutions FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (institution_id, associated_institution_id, relationship);
LOAD DATA LOCAL INFILE 'C:\\openalex\\institutions_counts_by_year.csv' REPLACE INTO TABLE openalex.institutions_counts_by_year FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (institution_id, year, works_count, cited_by_count);

LOAD DATA LOCAL INFILE 'C:\\openalex\\authors.csv' REPLACE INTO TABLE openalex.authors FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (`id`, `orcid`, `display_name`, `display_name_alternatives`, `works_count`, `cited_by_count`, `last_known_institution`, `works_api_url`, `updated_date`);
LOAD DATA LOCAL INFILE 'C:\\openalex\\authors_ids.csv' REPLACE INTO TABLE openalex.authors_ids FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (author_id, openalex, orcid, scopus, twitter, wikipedia, mag);
LOAD DATA LOCAL INFILE 'C:\\openalex\\authors_counts_by_year.csv' REPLACE INTO TABLE openalex.authors_counts_by_year FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (author_id, year, works_count, cited_by_count);

LOAD DATA LOCAL INFILE 'C:\\openalex\\concepts.csv' REPLACE INTO TABLE openalex.concepts FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (id, wikidata, display_name, level, description, works_count, cited_by_count, image_url, image_thumbnail_url, works_api_url, updated_date);
LOAD DATA LOCAL INFILE 'C:\\openalex\\concepts_ancestors.csv' REPLACE INTO TABLE openalex.concepts_ancestors FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (concept_id, ancestor_id);
LOAD DATA LOCAL INFILE 'C:\\openalex\\concepts_counts_by_year.csv' REPLACE INTO TABLE openalex.concepts_counts_by_year FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (concept_id, year, works_count, cited_by_count);
LOAD DATA LOCAL INFILE 'C:\\openalex\\concepts_ids.csv' REPLACE INTO TABLE openalex.concepts_ids FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (concept_id, openalex, wikidata, wikipedia, umls_aui, umls_cui, mag);
LOAD DATA LOCAL INFILE 'C:\\openalex\\concepts_related_concepts.csv' REPLACE INTO TABLE openalex.concepts_related_concepts FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (concept_id, related_concept_id, score);

LOAD DATA LOCAL INFILE 'C:\\openalex\\venues.csv' REPLACE INTO TABLE openalex.venues FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (id, issn_l, issn, display_name, publisher, works_count, cited_by_count, is_oa, is_in_doaj, homepage_url, works_api_url, updated_date);
LOAD DATA LOCAL INFILE 'C:\\openalex\\venues_ids.csv' REPLACE INTO TABLE openalex.venues_ids FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (venue_id, openalex, issn_l, issn, mag);
LOAD DATA LOCAL INFILE 'C:\\openalex\\venues_counts_by_year.csv' REPLACE INTO TABLE openalex.venues_counts_by_year FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (venue_id, year, works_count, cited_by_count);

LOAD DATA LOCAL INFILE 'C:\\openalex\\works.csv' REPLACE INTO TABLE openalex.works FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (id, doi, title, display_name, publication_year, publication_date, type, cited_by_count, is_retracted, is_paratext, cited_by_api_url, abstract_inverted_index);
LOAD DATA LOCAL INFILE 'C:\\openalex\\works_host_venues.csv' REPLACE INTO TABLE openalex.works_host_venues FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (work_id, venue_id, url, is_oa, version, license);
LOAD DATA LOCAL INFILE 'C:\\openalex\\works_alternate_host_venues.csv' REPLACE INTO TABLE openalex.works_alternate_host_venues FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (work_id, venue_id, url, is_oa, version, license);
LOAD DATA LOCAL INFILE 'C:\\openalex\\works_authorships.csv' REPLACE INTO TABLE openalex.works_authorships FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (work_id, author_position, author_id, institution_id, raw_affiliation_string);
LOAD DATA LOCAL INFILE 'C:\\openalex\\works_biblio.csv' REPLACE INTO TABLE openalex.works_biblio FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (work_id, volume, issue, first_page, last_page);
LOAD DATA LOCAL INFILE 'C:\\openalex\\works_concepts.csv' REPLACE INTO TABLE openalex.works_concepts FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (work_id, concept_id, score);
LOAD DATA LOCAL INFILE 'C:\\openalex\\works_ids.csv' REPLACE INTO TABLE openalex.works_ids FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (work_id, openalex, doi, mag, pmid, pmcid);
LOAD DATA LOCAL INFILE 'C:\\openalex\\works_mesh.csv' REPLACE INTO TABLE openalex.works_mesh FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (work_id, descriptor_ui, descriptor_name, qualifier_ui, qualifier_name, is_major_topic);
LOAD DATA LOCAL INFILE 'C:\\openalex\\works_open_access.csv' REPLACE INTO TABLE openalex.works_open_access FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (work_id, is_oa, oa_status, oa_url);
LOAD DATA LOCAL INFILE 'C:\\openalex\\works_referenced_works.csv' REPLACE INTO TABLE openalex.works_referenced_works FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (work_id, referenced_work_id);
LOAD DATA LOCAL INFILE 'C:\\openalex\\works_related_works.csv' REPLACE INTO TABLE openalex.works_related_works FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' (work_id, related_work_id);
